SUBSTRUCTURE_KEYS = 'MACCS_FULL'
BATCH_SIZE = 32
LR = 0.01
WEIGHT_DECAY = 0.001
SAMPLE_POS_FRACTION = 0.5
EPOCHS = int(1e4)

USE_EMBEDDING = True
EMBEDDING_DIM = 128
UNIQUE_ATOMS = 100
UNIQUE_CHARGES = 15
UNIQUE_BONDS = 20
MPNN_FEATURES_DIM = (2 * EMBEDDING_DIM) if USE_EMBEDDING else 2

USE_EMBEDDING = True
USE_MLP_FOR_PROCESSING = False

SAVE_MODEL_PATH = 'models/model.pt'
LOAD_MODEL_PATH = 'models/model.pt'
