SUBSTRUCTURE_KEYS = 'MACCS_FULL'
BATCH_SIZE = 128
LR = 0.01
WEIGHT_DECAY = 0.001
SAMPLE_POS_FRACTION = 0.5
EPOCHS = int(1e4)

EMBEDDING_DIM = 128
UNIQUE_ATOMS = 120
UNIQUE_CHARGES = 30
UNIQUE_BONDS = 15

USE_EMBEDDING = True
USE_MLP_FOR_PROCESSING = True

SAVE_MODEL_PATH = 'models/model.pt'
LOAD_MODEL_PATH = 'models/model.pt'
